targets:
  AloneSocialClub:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Resources
      - path: Supporting Files
    dependencies:
      - sdk: Foundation.framework
      - sdk: UIKit.framework
    attributes:
      ProvisioningStyle: Manual
    preBuildScripts:
    - name: Highlight TODO and FIXME
      script: |
        [[ -z "${GITHUB_WORKFLOW}" ]] && \
          ${PODS_ROOT}/SwiftLint/swiftlint lint \
            --config "${SRCROOT}/.swiftlint-todo.yml" \
            --path "${SRCROOT}/Projects/AloneSocialClub"
    - name: SwiftLint
      script: |
        [[ -z "${GITHUB_WORKFLOW}" ]] && \
          ${PODS_ROOT}/SwiftLint/swiftlint lint \
            --config "${SRCROOT}/.swiftlint.yml" \
            --path "${SRCROOT}/Projects/AloneSocialClub"
    settings:
      base:
        PRODUCT_NAME: AloneSocialClub
        PRODUCT_BUNDLE_IDENTIFIER: com.alonesocialclub.ios
        MARKETING_VERSION: 0.2.0
        CURRENT_PROJECT_VERSION: 2
        INFOPLIST_FILE: "$(SRCROOT)/Projects/AloneSocialClub/Supporting Files/Info.plist"
        TARGETED_DEVICE_FAMILY: 1
        DEVELOPMENT_TEAM: N2C267LBVY
        PROVISIONING_PROFILE_SPECIFIER: Alone Social Club App Store
        CODE_SIGN_ENTITLEMENTS: ${SRCROOT}/Projects/AloneSocialClub/Supporting Files/AloneSocialClub.entitlements
      configs:
        debug:
          CODE_SIGN_IDENTITY: Apple Developer
        release:
          CODE_SIGN_IDENTITY: Apple Distribution

  AloneSocialClubTests:
    templates: [UnitTest]
    templateAttributes:
      testTarget: AloneSocialClub

schemes:
  AloneSocialClub:
    build:
      targets:
        AloneSocialClub: all
        AloneSocialClubTests: [test]
    run:
      environmentVariables:
        OS_ACTIVITY_MODE: disable
    test:
      gatherCoverageData: true
      targets: [AloneSocialClubTests]
