name: AloneSocialClub
options:
  bundleIdPrefix: com.alonesocialcom
  deploymentTarget:
    iOS: 12.0
  defaultConfig: Release
  createIntermediateGroups: true
  transitivelyLinkDependencies: true
  tabWidth: 2
  indentWidth: 2

settings:
  base:
    SWIFT_VERSION: 5.1
    CLANG_ENABLE_MODULES: YES
    COPY_PHASE_STRIP: NO
    DEVELOPMENT_TEAM: N2C267LBVY

  configs:
    debug:
      SWIFT_OPTIMIZATION_LEVEL: -Onone
      ENABLE_TESTABILITY: YES
      ONLY_ACTIVE_ARCH: YES
      SWIFT_COMPILATION_MODE: incremental

    release:
      SWIFT_OPTIMIZATION_LEVEL: -O
      SWIFT_COMPILATION_MODE: wholemodule

schemes:
  AllTests:
    build:
      targets:
        AloneSocialClub: test
    test:
      gatherCoverageData: true
      targets:
        - AloneSocialClubTests

include:
  - Projects/templates.yml
  - Projects/AloneSocialClub/project.yml
