targets:
  AloneSocial:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Resources
      - path: Supporting Files
    dependencies:
      - sdk: Foundation.framework
      - sdk: UIKit.framework
    settings:
      PRODUCT_NAME: AloneSocial
      PRODUCT_BUNDLE_IDENTIFIER: com.alonesocialclub.ios
      MARKETING_VERSION: 0.1.0
      CURRENT_PROJECT_VERSION: 1
      INFOPLIST_FILE: "$(SRCROOT)/Projects/AloneSocial/Supporting Files/Info.plist"
      TARGETED_DEVICE_FAMILY: 1

  AloneSocialTests:
    templates: [UnitTest]
    templateAttributes:
      testTarget: AloneSocial

schemes:
  AloneSocial:
    build:
      targets:
        AloneSocial: all
        AloneSocialTests: [test]
    run:
      environmentVariables:
        OS_ACTIVITY_MODE: disable
    test:
      gatherCoverageData: true
      targets: [AloneSocialTests]
